### ISSUE TITLE
checklist for v0.1 release

### ISSUE THREAD

**Issue by sargunv** [sargunv/maplibre-compose#4]
- [ ] set up CI with formatting and testing
- [ ] write some real tests to establish patterns (full coverage is not a goal rn)
- [ ] write readme for end users
- [ ] write readme for contributers
- [ ] generate a documentation site with dokka(?) (full docs coverage is not a goal rn)
- [ ] build out a demo app showcasing features mentioned in readme as "supported"
- [ ] set up publishing
